<section>
    <div class="container">
        <div class="row" style="margin: 30px 0 50px 0;">
            <div class="col-md-6" style="padding-left: 0;">
                <div class="el-container">
                    <h4>🎊 <span class="orange-txt el3ers" style="font-size: 20px;">El3ers</span> <span class="el3ers-ar orange-txt">العرس</span> - <span class="el3ers" style="font-size: 20px;">Vos événements, notre passion !</span></h4>
                    <p>
                        Première plateforme en Algérie dédiée à la réservation et aux petites annonces autour de l’organisation d’événements.
                        Trouvez en quelques clics les meilleurs professionnels et artisans : salles, photographes, traiteurs, décorateurs, musiciens et bien plus encore !
                        Consultez les avis, tarifs et services, comparez les offres et faites votre choix en toute confiance.
                    </p>
                    <p>Avec El3ers, chaque événement devient un moment inoubliable.</p>
                </div>
            </div>
            <div class="col-md-6" style="padding-right: 0;">
                <div class="el-container" style="background: #FFF2FB;">
                    <h4 class="orange-txt"><i class="fa fa-info-circle"></i> Important</h4>
                    <p>Toute annonce ou message ne respectant pas notre règlement sera supprimé sans préavis.
                        Les annonces payantes sont soumises aux mêmes règles et ne feront l’objet d’aucun remboursement en cas de retrait pour non-conformité.
                        Cette liste de règles est non exhaustive, et El3ers se réserve le droit de supprimer tout contenu jugé inapproprié, sans avertissement ni notification préalable.
                        De tels retraits peuvent également entraîner la suspension temporaire ou définitive de l’accès au site.</p>
                </div>
            </div>
        </div>
    </div>
</section>
