<?php
echo $this->partial('ZfcUser/header', ['subPage' => 'myInformation']); ?>
<section class="zfc-user-page">
	<div class="container">
        <div class="title bio">
            <h3>
                <span class="title-dot"></span>
                Mes informations
            </h3>
        </div>

        <?php
        $form = $this->changeInformationForm;
        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/changeinformation'));
        $form->setAttribute('method', 'post');
        $form->setAttribute('class','form-horizontal');
        $form->get('submit')->setAttribute('class', 'btn btn-lg btn-primary');
        echo $this->form()->openTag($form);
        ?>
        <div class="row">
            <div class="col-md-6 col-xs-12">
                <?php if ($status === true) : ?>
                    <div class="alert alert-success">Vos informations ont été modifiées avec succès</div>
                <?php elseif ($status === false) : ?>
                    <div class="alert alert-error"><?php echo $this->translate('Unable to update your information. Please try again.'); ?></div>
                <?php endif; ?>
                <h1>
                    <?php echo $this->zfcUserIdentity()->getFirstname() . ' ' . $this->zfcUserIdentity()->getLastname(); ?>
                </h1>
                <hr>
                <?php
                $emailElement = $form->get('username');
                $emailElement->setValue($this->zfcUserIdentity()->getEmail());
                $phoneElement = $form->get('mobilephone');
                $phoneElement->setValue($this->zfcUserIdentity()->getPhoneMobile());
                ?>
                <div class="form-group">
                    <div class="col-sm-12">
                        <?php echo $this->formLabel($emailElement); ?>
                        <?php echo $this->formInput($emailElement)?>
                        <?php echo $this->formElementErrors($emailElement); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-12">
                        <?php echo $this->formLabel($phoneElement); ?>
                        <?php echo $this->formInput($phoneElement)?>
                        <?php echo $this->formElementErrors($phoneElement); ?>
                    </div>
                </div>
                <div class="form-group" style="margin-top: 20px;">
                    <div class="col-sm-12">
                    <?php
                     // echo $this->formInput($form->get('csrf'));
                     // echo $this->formInput($form->get('submit'));
                    ?>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-12" style="display: flex; align-items: center; justify-content: center">
                <i class="fa fa-users" style="font-size: 250px;color: #eee"></i>
            </div>

        </div>
        <?php
            echo $this->form()->closeTag();
        ?>
    </div>
</section>
<section class="hidden-xs">
    <?php echo $this->partial('ZfcUser/footer'); ?>
</section>
<?php echo $this->partial('albook/footer-html'); ?>
