<?php echo $this->partial('ZfcUser/header', ['subPage' => 'myPassword']); ?>
<section class="zfc-user-page">
    <div class="container">
        <div class="title bio">
            <h3>
                <span class="title-dot"></span>
                <?php echo $this->translate('Changement de mot de passe', __NAMESPACE__); ?>
            </h3>
        </div>

        <?php
        $form = $this->changePasswordForm;
        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/changemypass'));
        $form->setAttribute('method', 'post');
        $form->setAttribute('class', 'form-horizontal');
        $form->get('submit')->setAttribute('class', 'btn btn-lg btn-primary');
        $emailElement = $form->get('identity');
        $emailElement->setValue($this->zfcUserIdentity()->getEmail());
        echo $this->form()->openTag($form);
        ?>

        <div class="row">
            <div class="col-md-6 col-xs-12">

                <?php if ($status === true) : ?>
                    <div class="alert alert-success"><?php echo $this->translate('Password changed successfully.'); ?></div>
                <?php elseif ($status === false) : ?>
                    <div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
                <?php endif; ?>

                <?php echo $this->formInput($form->get('identity')); ?>
                <?php echo $this->formElementErrors($form->get('identity')); ?>

                <div class="form-group">
                    <div class="col-sm-12">
                        <?php echo $this->formLabel($form->get('credential')); ?>
                        <?php echo $this->formInput($form->get('credential')); ?>
                        <?php echo $this->formElementErrors($form->get('credential')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-12">
                        <?php echo $this->formLabel($form->get('newCredential')); ?>
                        <?php echo $this->formInput($form->get('newCredential')); ?>
                        <?php echo $this->formElementErrors($form->get('newCredential')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-12">
                        <?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
                        <?php echo $this->formInput($form->get('newCredentialVerify')); ?>
                        <?php echo $this->formElementErrors($form->get('newCredentialVerify')); ?>
                    </div>
                </div>

                <div class="form-group" style="margin-top: 20px;">
                    <div class="col-sm-12">
                        <?php echo $this->formInput($form->get('submit')); ?>
                    </div>
                </div>

            </div>
            <div class="col-md-6 col-xs-12" style="display: flex; align-items: center; justify-content: center">
                <i class="fa fa-unlock" style="font-size: 250px; color: #eee"></i>
            </div>
        </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>
<section class="hidden-xs">
    <?php echo $this->partial('ZfcUser/footer'); ?>
</section>
<?php echo $this->partial('albook/footer-html'); ?>